"""Unit tests for the macOS concealed/transient/auto-generated pasteboard
type skip logic (AC5). Exercises only the pure helper in
vendor/ClipCascade_Desktop/src/clipboard/sensitive.py -- no AppKit import,
so this runs on any host/OS with no display server or pyobjc installed.
"""

from clipboard.sensitive import should_skip_pasteboard_types


def test_concealed_type_skips():
    assert should_skip_pasteboard_types(["org.nspasteboard.ConcealedType"]) is True


def test_transient_type_skips():
    assert (
        should_skip_pasteboard_types(
            ["public.utf8-plain-text", "org.nspasteboard.TransientType"]
        )
        is True
    )


def test_autogenerated_type_skips():
    assert should_skip_pasteboard_types(["org.nspasteboard.AutoGeneratedType"]) is True


def test_multiple_concealed_markers_still_skip():
    assert (
        should_skip_pasteboard_types(
            [
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "public.utf8-plain-text",
            ]
        )
        is True
    )


def test_normal_text_types_do_not_skip():
    assert (
        should_skip_pasteboard_types(
            ["public.utf8-plain-text", "public.utf16-plain-text", "public.rtf"]
        )
        is False
    )


def test_normal_image_types_do_not_skip():
    assert should_skip_pasteboard_types(["public.png", "public.tiff"]) is False


def test_empty_list_does_not_skip():
    assert should_skip_pasteboard_types([]) is False


def test_none_does_not_skip():
    assert should_skip_pasteboard_types(None) is False


def test_case_variation_does_not_match():
    # The nspasteboard.org UTIs are exact, case-sensitive strings. A
    # differently-cased variant of the real flag must NOT be treated as a
    # match -- guards against silently loosening the check to a
    # case-insensitive one.
    assert should_skip_pasteboard_types(["ORG.NSPASTEBOARD.CONCEALEDTYPE"]) is False
    assert should_skip_pasteboard_types(["org.nspasteboard.concealedtype"]) is False


def test_exact_real_world_casing_matches():
    # Sanity check against the literal casing 1Password/Bitwarden/KeePassXC
    # actually publish on the pasteboard.
    assert should_skip_pasteboard_types(["org.nspasteboard.ConcealedType"]) is True
    assert should_skip_pasteboard_types(["org.nspasteboard.TransientType"]) is True
    assert should_skip_pasteboard_types(["org.nspasteboard.AutoGeneratedType"]) is True
